services:
  - type: web
    name: lending-app
    runtime: docker
    repo: https://github.com/muchirigikunju22/lending-app.git
    plan: free
    branch: main
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: lending-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lending-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: lending-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: lending-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: lending-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      - key: SPRING_FLYWAY_ENABLED
        value: "true"

databases:
  - name: lending-db
    databaseName: lendingdb
    user: lendinguser
    plan: free